name: Innovation Insider
favicon: null
layout_spectrum: 0.6919054919853806
typography_spectrum: 0.9266385831870139
title: "Creating what's next¡"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.09398456127382815
  saturation: 0.5
  rhythmicContrast: 0.24396836385130882
purpose: []
