name: Innovation Insider
favicon: null
layout_spectrum: 0.75736
typography_spectrum: 0.95551
title: 'Innovation Insider : Looking for the next'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a1a1a1'
    - '#d9d9d9'
    - '#717171'
    - '#1e1e1e'
    - '#4a4a4a'
  brandStrength: 0.5
  lightness: 0.09398456127382815
  saturation: 0.5
  rhythmicContrast: 0.24396836385130882
purpose: []
