name: Innovation Insider
favicon: null
layout_spectrum: 0.25495
typography_spectrum: 0.96513
title: 'Innovation Insider : Looking for the next'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf9f9'
    - '#000000'
    - '#4e4d4d'
    - '#868686'
    - '#1e1e1e'
  brandStrength: 0.5
  lightness: 0.09398456127382815
  saturation: 0.5
  rhythmicContrast: 0.24396836385130882
purpose: []
