name: Innovation Insider
favicon: null
layout_spectrum: 0.75736
typography_spectrum: 0.95551
title: "Creating what's next¡"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7dfe0'
    - '#102641'
    - '#1298bc'
    - '#ef9438'
    - '#4e5457'
  brandStrength: 0.5
  lightness: 0.09398456127382815
  saturation: 0.5
  rhythmicContrast: 0.24396836385130882
purpose: []
